### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Huzefa-Aamir** [Hanan-Li/masked-face-recognition#2]
What data sets are you using?
Pasting the errors here for you to see what modules are missing. Let me know how to resolve them/ upload the directories please!!
1. File "face_verification_one_shot.py", line 50, in <module>
    for folder in os.listdir(PATH):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/classes/CS6220/Final/labeled_face_dataset
2.  File "verify_all_pairs.py", line 216, in <module>
    directory = sys.argv[1]
IndexError: list index out of range
3.   File "validate_lfw.py", line 25, in <module>
    orig_img_ds = datasets.ImageFolder(data_dir, transform=None)
  File "C:\Users\***\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 253, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "C:\Users\***\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 126, in __init__
    classes, class_to_idx = self._find_classes(self.root)
  File "C:\Users\***\anaconda3\lib\site-packages\torchvision\datasets\folder.py", line 164, in _find_classes
    classes = [d.name for d in os.scandir(dir) if d.is_dir()]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'lfw_complete\\lfw'
Note: The asterisks in the path are for privacy issues.

**Comment by Hanan-Li** [comment]
Hi, sorry for the late reply, I completely forgot about this.

For a lot of the files and datasets, we hardcoded the directories from our own computers (since this is a school project that we were rushing to get done in the end).

This means to solve the problems listed in 1 and 3, you would have to use your own image directories. I will clean this repo up when I have time to make this easier.

For problem 2, when you run validate_lfw.py in the command line, you would have to type the directory of where the images are as a command line argument.

I will clean this repo up to make it more intuitive when I have time.

Thanks for understanding.
